# Generated by Django 4.0.1 on 2022-01-27 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrics', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField()),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('-created_date',),
            },
        ),
    ]
